name: predicting_the_wind
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - folium
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pytz
  - scipy
  - scikit-learn
  - pip:
    - brightwind