name: predicting_the_wind
channels:
  - anaconda
  - conda-forge
  - damianavila82
  - defaults
dependencies:
  - folium
  - jupyterlab
  - matplotlib
  - netcdf4
  - numpy
  - pandas
  - pip
  - pytz
  - rise
  - scipy
  - scikit-learn
  - pip:
    - brightwind
    - hide_code==0.5.2
    - jupyter_contrib_nbextensions
    - pdfkit