name: predicting_the_wind
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - abseil-cpp
  - affine=2.3.0
  - alembic=1.4.1
  - appnope=0.1.0
  - arrow-cpp=0.16.0
  - asn1crypto=1.3.0
  - attrs=19.3.0
  - aws-sdk-cpp=1.7.164
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.1
  - boost-cpp=1.72.0
  - branca=0.4.0
  - brotli=1.0.7
  - bzip2=1.0.8
  - c-ares=1.15.0
  - ca-certificates=2019.11.28
  - cairo=1.16.0
  - cdsapi=0.1.6
  - certifi=2019.11.28
  - cffi=1.14.0
  - cfitsio=3.470
  - cftime=1.0.4.2
  - chardet=3.0.4
  - click=7.0
  - click-plugins=1.1.1
  - cliff=2.15.0
  - cligj=0.5.0
  - cmd2=0.9.15
  - colorama=0.4.3
  - colorlog=4.1.0
  - cryptography=2.8
  - curl=7.68.0
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.2
  - defusedxml=0.6.0
  - entrypoints=0.3
  - expat=2.2.9
  - folium=0.10.1
  - fontconfig=2.13.1
  - freetype=2.9.1
  - freexl=1.0.5
  - geos=3.8.0
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - gflags=2.2.2
  - giflib=5.2.1
  - glib=2.58.3
  - glog=0.4.0
  - grpc-cpp=1.27.3
  - hdf4=4.2.13
  - hdf5=1.10.5
  - icu=64.2
  - idna=2.8
  - importlib_metadata=1.5.0
  - intel-openmp=2020.0
  - ipykernel=5.1.4
  - ipython=7.12.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - jedi=0.16.0
  - jinja2=2.11.1
  - joblib=0.14.1
  - jpeg
  - json-c=0.13.1
  - json5=0.9.1
  - jsonschema=3.2.0
  - jupyter_client=6.0.0
  - jupyter_console=6.1.0
  - jupyter_core=4.6.3
  - jupyterlab=1.2.6
  - jupyterlab_server=1.0.6
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.4
  - libclang=9.0.1
  - libcurl=7.68.0
  - libcxx=9.0.1
  - libdap4=3.20.4
  - libedit=3.1.20170329
  - libevent=2.1.10
  - libffi=3.2.1
  - libgdal=3.0.4
  - libgfortran=3.0.1
  - libiconv=1.15
  - libkml=1.3.0
  - libllvm9=9.0.1
  - libnetcdf=4.7.3
  - libpng=1.6.37
  - libpq=12.2
  - libprotobuf=3.11.4
  - libsodium=1.0.17
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.1.0
  - libwebp=1.0.2
  - libxml2=2.9.10
  - llvm-openmp=4.0.1
  - lz4-c=1.8.3
  - mako=1.1.0
  - markupsafe=1.1.1
  - matplotlib=3.1.3
  - matplotlib-base=3.1.3
  - mistune=0.8.4
  - mkl=2019.5
  - mkl-service=2.3.0
  - mkl_fft=1.0.15
  - mkl_random=1.1.0
  - more-itertools=8.2.0
  - nbconvert=5.6.1
  - nbformat=5.0.4
  - ncurses=6.1
  - netcdf4=1.5.3
  - notebook=6.0.3
  - nspr=4.20
  - nss=3.47
  - numpy=1.18.1
  - numpy-base=1.18.1
  - openjpeg=2.3.1x
  - openssl=1.1.1d
  - optuna=1.2.0
  - pandas=1.0.1
  - pandoc=2.9.2
  - pandocfilters=1.4.2
  - parquet-cpp=1.5.1
  - parso=0.6.1
  - pbr=5.4.2
  - pcre=8.44
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.0.2
  - pixman=0.38.0
  - pluggy=0.13.1
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=12.2
  - prettytable=0.7.2
  - proj=6.3.1
  - prometheus_client=0.7.1
  - prompt_toolkit=3.0.3
  - ptyprocess=0.6.0
  - py=1.8.1
  - pyarrow=0.16.0
  - pycparser=2.19
  - pygments=2.5.2
  - pyopenssl=19.1.0
  - pyparsing=2.4.6
  - pyperclip=1.7.0
  - pyqt=5.12.3
  - pyrsistent=0.15.7
  - pysocks=1.7.1
  - python=3.7.6
  - python-dateutil=2.8.1
  - python-editor=1.0.4
  - python_abi=3.7
  - pytz=2019.3
  - pyyaml=5.3
  - pyzmq=19.0.0
  - qt=5.12.5
  - qtconsole=4.7.1
  - qtpy=1.9.0
  - rasterio=1.1.3
  - re2=2019.08.01
  - readline=8.0
  - requests=2.22.0
  - rise=5.6.1
  - scikit-learn=0.22.1
  - scipy=1.4.1
  - send2trash=1.5.0
  - setuptools=45.2.0
  - six=1.14.0
  - snappy=1.1.8
  - snuggs=1.4.7
  - sqlalchemy=1.3.13
  - sqlite=3.30.1
  - stevedore=1.30.1
  - tbb=2018.0.5
  - terminado=0.8.3
  - testpath=0.4.4
  - thrift-cpp=0.13.0
  - tiledb=1.7.0
  - tk=8.6.10
  - tornado=6.0.3
  - tqdm=4.42.1
  - traitlets=4.3.3
  - tzcode=2019a
  - urllib3=1.25.8
  - vincent=0.4.4
  - wcwidth=0.1.8
  - webencodings=0.5.1
  - wheel=0.34.2
  - widgetsnbextension=3.5.1
  - xerces-c=3.2.2
  - xz=5.2.4
  - yaml=0.2.2
  - zeromq=4.3.2
  - zipp=3.0.0
  - zlib=1.2.11
  - zstd=1.4.4
  - pip:
    - brightwind==1.0.0
    - hide-code==0.5.5
    - jupyter==1.0.0
    - packaging==20.3
    - pdfkit==0.6.1
    - pyqt5-sip==4.19.18
    - pyqtwebengine==5.12.1
    - pytest==5.3.5

