name: Push to Docker Hub
on:
  push:
    paths:
    - 'environment.yml'

jobs:
  Binder:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: cache binder build on mybinder.org
        uses: machine-learning-apps/repo2docker-action@0.2
        with:
          NO_PUSH: true
          MYBINDERORG_TAG: ${{ github.event.ref }}
